# Generated by Django 5.2.5 on 2025-08-14 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewhelpfulness',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpfulness_votes', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='reviewhelpfulness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['course', 'is_approved'], name='reviews_course__f254ac_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status'], name='reviews_status_12ddaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpfulness',
            unique_together={('user', 'review')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewreport',
            unique_together={('reporter', 'review')},
        ),
    ]
